version: '2'

services:
  jenkins:
    image: jenkins:alpine
    container_name: jenkins
    hostname: jenkins
    privileged: true
    ports:
      - "18080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  haproxy:
    build: haproxy
    container_name: haproxy
    links:
      - jenkins
    ports:
      - 80:80
      - 443:443

  executor-node:
    image: jenkins_executor
    build: jenkins_executor
    container_name: jenkins_executor
    privileged: true
    links:
      - jenkins
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
